allowBuilds:
  "@google/genai": true
  "@parcel/watcher": true
  better-sqlite3: true
  esbuild: true
  protobufjs: true
  unrs-resolver: true
  vue-demi: true

overrides:
  "@tiptap/core": 3.27.3
  "@tiptap/pm": 3.27.3
  "@tiptap/y-tiptap": ^3.0.6
  axios: ^1.15.0
  h3-next: npm:h3@2.0.1-rc.18
  serialize-javascript: 7.0.5
  unhead: ^2.1.13

patchedDependencies:
  "@nuxt/ui@4.9.0": patches/@nuxt__ui@4.9.0.patch
