import type { CategoryName } from "../constants/categories";

export interface NewsItem {
  title: string;
  summary: string;
  content: string;
  source: string;
  publishedAt: string;
  category: CategoryName;
  url?: string;
  favicon?: string;
  credibilityScore?: number; // Overall 0-1 credibility score
}

export interface ApiResponse<T = unknown> {
  success: boolean;
  data: T;
  count?: number;
  timestamp: string;
}

// --- NEW TYPES FOR SYNTHESIZED BRIEFING ---

export interface BriefingSource {
  title: string;
  source: string;
  url?: string;
  favicon?: string;
  credibilityScore: number;
}

export interface NewsBriefing {
  mainHeadline: string;
  executiveSummary: string;
  thematicAnalysis: string;
  overallCredibilityScore: number;
  sourcesProcessed: BriefingSource[];
  isAiFallback?: boolean;
  publishTimeRange?: string;
}

// --- CLUSTERED STORIES & LONG-TERM TRENDS ---

/** JLPT proficiency bands, easiest (N5) to hardest (N1). */
export type JlptLevel = "N5" | "N4" | "N3" | "N2" | "N1";

export interface VocabItem {
  term: string;
  reading: string;
  meaning: string;
  jlptLevel: JlptLevel;
  exampleSentence: string;
}

export interface GrammarNote {
  pattern: string;
  explanation: string;
  exampleSentence: string;
}

/**
 * Japanese-learning lesson content attached to a Story, generated by the MCP
 * agent from the story's Japanese-language source(s). All fields optional — a
 * story built purely from English-language coverage carries no lesson.
 */
export interface StoryLesson {
  originalText?: string;
  furiganaText?: string;
  vocabList?: VocabItem[];
  grammarNotes?: GrammarNote[];
  difficultyLevel?: JlptLevel;
}

export interface StorySource {
  title: string;
  source: string;
  url: string;
  publishedAt: string;
  favicon?: string;
  credibilityScore: number;
  addedAt: number; // timestamp in ms
  category?: string;
}

export interface Story extends StoryLesson {
  id: string;
  headline: string;
  summary: string;
  thematicAnalysis: string;
  articleCount: number;
  firstSeen: number; // timestamp ms
  lastUpdated: number; // timestamp ms
  trendScore: number;
  sources: StorySource[];
  categories: string[];
  isSummarized?: boolean;
}
