<template>
  <DocsBook slug="data-integrity">
    <template #lede>
      NipponDaily teaches Japanese, so a wrong reading, meaning or origin is a
      bug, not a typo. Accuracy comes from sources, never from a person's or a
      model's memory. The only hand-written text is a <strong>headline</strong>;
      everything else is generated by <code>pnpm data:words</code> from JMdict,
      KANJIDIC2, pinned Wiktionary text, a pinned Tatoeba export and a pinned
      pitch accent list that a second dictionary has to bear out.
    </template>

    <h2>Where the data comes from</h2>
    <div class="table-wrap">
      <table>
        <thead>
          <tr>
            <th>Data</th>
            <th>Source</th>
            <th>Lives in</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>JLPT vocabulary ({{ JLPT_RANGE }})</td>
            <td>
              <a
                :href="SOURCES['jlpt-word-list'].url"
                target="_blank"
                rel="noopener"
                >{{ SOURCES["jlpt-word-list"].name }}</a
              >
              (one CSV per level), cross-referenced against the JMdict and
              KANJIDIC2 files
              <a :href="SOURCES.edrdg.url" target="_blank" rel="noopener">{{
                SOURCES.edrdg.holderShort
              }}</a>
              publishes, pinned by size and checksum
            </td>
            <td><code>data/reference/n{5,4,3,2,1}-reference.json</code></td>
          </tr>
          <tr>
            <td>Origins</td>
            <td>
              <a
                :href="SOURCES.wiktionary.url"
                target="_blank"
                rel="noopener"
                >{{ SOURCES.wiktionary.name }}</a
              >
              Etymology sections, read from one pinned, dated dump (via
              {{ SOURCES.wiktionary.via.name }})
            </td>
            <td><code>data/reference/etymology/</code></td>
          </tr>
          <tr>
            <td>Example sentences</td>
            <td>
              <a :href="SOURCES.tatoeba.url" target="_blank" rel="noopener">{{
                SOURCES.tatoeba.name
              }}</a>
              sentences with an English translation that its own index lists
              under the word, read from one pinned, dated export; the readings
              over their kanji are Tatoeba's own furigana of each sentence, each
              checked against KANJIDIC2 or JMdict and kept only where a
              contributor wrote it or kuromoji, UniDic or Tatoeba's index agrees
            </td>
            <td><code>data/reference/sentences/</code></td>
          </tr>
          <tr>
            <td>Pitch accent</td>
            <td>
              The accent list of
              <a :href="SOURCES.kanjium.url" target="_blank" rel="noopener">{{
                SOURCES.kanjium.name
              }}</a
              >, read at one pinned commit: the mora after which the pitch
              falls, for a word whose exact spelling and reading are both on a
              line of it. An accent is kept only where
              <a :href="SOURCES.unidic.url" target="_blank" rel="noopener">{{
                SOURCES.unidic.name
              }}</a
              >, which annotates its own accent types, gives the same one for
              that spelling and reading; the snapshot lists the words that lost
              one
            </td>
            <td><code>data/reference/pitch.json</code></td>
          </tr>
          <tr>
            <td>Kanji pages</td>
            <td>
              KANJIDIC2's record of every kanji the entries are written with,
              copied from the level snapshots
            </td>
            <td><code>data/reference/kanji.json</code></td>
          </tr>
          <tr>
            <td>Stroke order</td>
            <td>
              <a :href="SOURCES.kanjivg.url" target="_blank" rel="noopener">{{
                SOURCES.kanjivg.name
              }}</a>
              strokes in drawing order, read from one pinned release and kept
              for a kanji only where KANJIDIC2 counts the same number of strokes
            </td>
            <td><code>data/reference/strokes.json</code></td>
          </tr>
          <tr>
            <td>Daily words</td>
            <td>
              Generated from the word-list snapshots, the Etymology pins, the
              sentence snapshot and the pitch snapshot, plus the hand-written
              headlines in
              <code>data/word-plan/</code>
            </td>
            <td><code>data/words/YYYY-MM.json</code></td>
          </tr>
        </tbody>
      </table>
    </div>
    <p>
      The evidence is committed, because dictionary data isn't in the repo's
      tests and etymology isn't in a dictionary at all. CI checks every entry
      against it, offline. Word-list commits are pinned in
      <code>scripts/word-list-source.mjs</code>, and the JMdict and KANJIDIC2
      files in <code>scripts/lib/jmdict.mjs</code> (EDRDG overwrites both every
      day, so a pin is the only way to rebuild the same data, and the files are
      kept beside the code, git-ignored), so no builder can fetch different
      upstream data for the same level. The Wiktionary dump's date and checksum
      are pinned in <code>scripts/lib/wiktionary-dump.mjs</code>; the dump
      itself is too large to commit, so only the sections the entries quote are.
      A pool word with no Etymology section for its reading cannot become an
      entry (<NuxtLink to="/docs/words">Daily words</NuxtLink>). The Tatoeba
      export is pinned the same way, by size and checksum in
      <code>scripts/lib/tatoeba-export.mjs</code>, and is too large to commit,
      so only the sentences the entries show are. The accent list, the UniDic
      archive that checks it and the KanjiVG release are pinned by size and
      checksum in <code>scripts/build-pitch-reference.mjs</code>,
      <code>scripts/lib/unidic-accent.mjs</code> and
      <code>scripts/build-strokes-reference.mjs</code>, and only the accents and
      strokes the entries use are committed.
    </p>
    <p>
      Data is processed offline once the pinned files are in place. The
      reference builders read the pinned JMdict and KANJIDIC2 files from the
      repo root (downloading a missing one, checksum-verified) and fetch the
      word lists;
      <code>pnpm data:pitch</code> and <code>pnpm data:strokes</code> download
      their pinned files the first time and cache them (the UniDic archive is
      large, about half a gigabyte, and only its dictionary file is kept);
      <code>pnpm data:sentences</code> reuses the same JMdict and KANJIDIC2
      files to check furigana, and every other step, from
      <code>pnpm data:etymology</code> to <code>pnpm data:kanji</code>,
      <code>pnpm data:words</code> and the tests, reads only local files. The
      running site reads none of these sources: the data is committed and served
      by the app.
    </p>

    <h2>How an entry is built</h2>
    <DocDiagram
      label="Sources become committed snapshots, and the generator builds every entry from the snapshots alone"
      :nodes="build.nodes"
      :edges="build.edges"
    />
    <p>
      <code>scripts/lib/word-entry.mjs</code> builds an entry from sources only
      (<code>scripts/generate-word-entries.mjs</code> runs it, and fetches
      nothing). Each step refuses rather than guess:
    </p>
    <ul>
      <li>
        <code>pickSections</code> picks the Wiktionary section whose declared
        reading covers the word's.
      </li>
      <li>
        <code>evidenceLines</code> yields one verbatim quote per line, minus
        Wikipedia furniture.
      </li>
      <li>
        <code>parseMorphemes</code> reads
        <code>A (a, “gloss”) + B (b, “gloss”)</code> chains and keeps them only
        if the parts spell the word and join to its reading (rendaku allowed).
        It also accepts a stem glossed through its base verb (缶詰), a dropped
        okurigana (出る → 出口) and bare kana parts (お), and picks nothing when
        two different splits fit.
      </li>
      <li>
        <code>parseLiteral</code> pairs a “warm + spring” style gloss with
        KANJIDIC2's unambiguous per-kanji readings; <code>parseLoan</code>
        handles loanwords.
      </li>
      <li>
        <code>parseKanji</code> is the last resort for a word written with kanji
        (and the okurigana after them) that the text doesn't split: one part per
        kanji, with the okurigana that follow it (手続き is 手 + 続き, 言い出す
        is 言い + 出す), KANJIDIC2's reading and a meaning the text or the
        JMdict meaning already uses, marked
        <code>glossSource: "kanjidic2"</code>. It is refused for ateji,
        jukujikun, an ambiguous split, kana KANJIDIC2 does not list as okurigana
        (何でも), and a single kanji with its okurigana, which would only repeat
        the word.
      </li>
      <li>
        <code>processesOf</code> finds keyword tags in the quoted text and adds
        what JMdict, a source independent of Wiktionary, records for the matched
        sense: a coinage made in Japan, an ateji or jukujikun spelling, a loan
        source (<code>jmdictFactsOf</code>). <code>stratumOf</code> analyses
        KANJIDIC2's on and kun readings, and takes a JMdict loan source as the
        loanword layer unless the cited text names Chinese.
      </li>
    </ul>

    <h3 id="provenance">What each field comes from</h3>
    <div class="table-wrap">
      <table>
        <thead>
          <tr>
            <th>Field</th>
            <th>Source</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="row in provenance" :key="row.field">
            <td>
              <code>{{ row.field }}</code>
            </td>
            <td><RichText :text="row.source" /></td>
          </tr>
        </tbody>
      </table>
    </div>

    <h2 id="ai">Where AI may help, and where it may not</h2>
    <p>
      A model's output can be wrong in ways that read as confident, so AI is
      only given tasks whose output is allowed to be inaccurate: nothing it
      produces is shown to a reader as a fact unless a source backs it.
    </p>
    <ul>
      <li>
        <strong>OK:</strong> choosing which words go in a month (a poor pick
        costs nothing; the generator refuses a word with no usable source),
        drafting a headline (a hook, not a claim; a test limits its Japanese to
        what the evidence or pool contains), and writing code or tests, which CI
        then checks.
      </li>
      <li>
        <strong>Not OK:</strong> supplying a reading, meaning, level, layer,
        morpheme split, etymology or any other claim about a word.
      </li>
    </ul>
    <p>
      Before handing a task to a model, ask:
      <em
        >if this came back wrong, would a check catch it or would it simply not
        matter?</em
      >
      If neither, it must come from a source. The same goes for any new
      feature's data.
    </p>

    <h2>What the checks prove</h2>
    <DocDiagram
      label="The content tests read the committed evidence and every entry; a wrong claim fails CI"
      :nodes="checks.nodes"
      :edges="checks.edges"
    />
    <p>
      The content tests (<code>test/content/</code>, their own Vitest project,
      run by <code>pnpm test</code> in CI) regenerate every month and check each
      entry independently of the generator, so a generator bug can't vouch for
      itself.
    </p>
    <ul>
      <li>
        <strong>Generation</strong> (<code>word-generation.test.ts</code>): a
        committed entry equals, field for field, what the generator derives, so
        a derived field can't be edited by hand or left stale.
      </li>
      <li>
        <strong>Catalogue</strong>: every date and term is unique, no day
        between the first entry and the last is missing (the first and last
        months may be partial), and entries are sorted.
      </li>
      <li>
        <strong>Every entry</strong> (<code>words.test.ts</code>):
        <ul>
          <li>
            the term, reading, level and meaning equal the word list's, and its
            layer and processes are ones the site knows;
          </li>
          <li>
            <code>pos</code> holds only tags JMdict gives that word, and
            <code>register</code>, <code>field</code> and <code>dialect</code>
            only tags every matched sense carries;
          </li>
          <li>
            every <code>sources[].quote</code> is found
            <strong>verbatim</strong> (modulo whitespace and direction marks) in
            a Wiktionary Etymology section declared for the entry's
            <em>own reading</em>, from the dump the entry names (a page like
            大人 has one section per reading);
          </li>
          <li>
            the morphemes literally spell the word and join to
            <code>kana</code>; each non-<code>irregular</code> single-kanji
            morpheme has a reading KANJIDIC2 lists and a gloss KANJIDIC2 or the
            cited text backs;
          </li>
          <li>
            the headline mentions only Japanese the entry's evidence or the pool
            contains;
          </li>
          <li>
            an <code>unclear</code> entry quotes a hedged line, no snapshot pin
            is orphaned, each pin sits in the shard of the month that plans its
            word, and the snapshot records its source and licence.
          </li>
        </ul>
      </li>
      <li>
        <strong>JMdict, independently</strong>
        (<code>jmdict-crosscheck.test.ts</code>): an entry's priority codes are
        ones JMdict gives its spelling or reading; its register, field and
        dialect are exactly the tags every matched sense carries (and the
        register tags still occur in the pinned JMdict, so a renamed tag cannot
        silently stop matching); a word written with kanji that JMdict marks as
        a coinage made in Japan or an ateji, gikun or jukujikun spelling or
        reading carries that process; a European loan source means the borrowing
        process and the loanword layer (unless the cited text itself puts
        Chinese forward and hedges, as for 缶). It only confirms: the JMdict
        file pinned here gives no loan source for many loanwords (カメラ,
        ノート), so silence from JMdict proves nothing.
      </li>
      <li>
        <strong>Example sentences</strong> (<code>examples.test.ts</code>): each
        sentence is the committed snapshot's, holds the form it says the word
        takes, is a form of that word (its own spelling, an inflection that
        keeps the first character, or kana), has a translation and a readable
        length, and the snapshot names the export it came from. The sentences
        are not reviewed one by one: the export is the community's, and a short
        filter keeps out the plainly unsuitable; of a word's qualifying
        sentences, those with every kanji read come first. Each sentence's
        furigana joins back to its text, puts a reading only over kanji, in
        hiragana, and never across the edge of the word's form; almost every
        kanji of the sentences shown has one; the snapshot says how readings
        were checked.
      </li>
      <li>
        <strong>Pitch accent</strong> (<code>pitch.test.ts</code>): the snapshot
        names its source, licence and the file it was read from, holds only
        words in the catalogue with their own reading, gives each accent as a
        whole number no larger than the word's count of morae, and every entry
        shows the snapshot's accents and no others. The second source is named
        too, and every word that lost an accent is listed with what each source
        said, adding up to what was kept.
      </li>
      <li>
        <strong>Kanji</strong> (<code>kanji.test.ts</code>):
        <code>data/reference/kanji.json</code> holds exactly the kanji the
        entries are written with, each as the level snapshots have it.
      </li>
      <li>
        <strong>Stroke order</strong> (<code>strokes.test.ts</code>): the
        snapshot names its source, licence and release, holds only kanji of
        <code>kanji.json</code>, each with as many strokes as KANJIDIC2 counts,
        and covers nearly every kanji the entries use.
      </li>
      <li>
        <strong>Every word-list word, at every level</strong>
        (<code>vocabulary.test.ts</code> in <code>test/content/</code> and
        <code>test/content/{n4,n3,n2,n1}/</code>): it is in JMdict with that
        reading, has no meaning that reverses JMdict's, has its reading attested
        (<code>reading-attested.test.ts</code>), and every enrichment in
        <code>shared/meanings.ts</code> is backed by JMdict. A staleness check
        fails if a reference file no longer matches what
        <code>servedVocab()</code> would produce.
      </li>
    </ul>

    <aside class="note">
      <span class="note-title">What these checks cannot prove</span>
      <p>
        That Wiktionary is <em>right</em> (only that the dump says so), that
        JMdict's tags suit every usage, or that a headline is a fair hook. Where
        Wiktionary hedges, the entry quotes the hedge and flags it instead of
        choosing a winner.
      </p>
      <p>
        The dump is machine-extracted, and two of its faults are known. It drops
        Wiktionary's “etymology incomplete” banners, so a word the page marks
        incomplete may not be flagged unclear. And it can attach one reading's
        etymology to another (道 みち received the Middle Chinese section of
        どう). The generator refuses a native reading whose section opens “From
        Middle Chinese”, but a swap between two readings of the same kind would
        not be caught, so read each new entry once.
      </p>
    </aside>

    <p>
      To change a word or add a month, see
      <NuxtLink to="/docs/authoring">Adding and fixing words</NuxtLink>.
    </p>

    <h2 id="data-attribution">Attribution</h2>
    <p>
      Written once in <code>shared/sources.ts</code>; the footer, each entry's
      citation and the README read it from there.
    </p>
    <div class="note">
      <p
        v-for="source in DATA_SOURCES"
        :key="source.id"
        :data-testid="`credit-${source.id}`"
      >
        <RichText :text="source.credit" />
      </p>
    </div>
  </DocsBook>
</template>

<script setup lang="ts">
import DocsBook from "../../components/DocsBook.vue";
import DocDiagram from "../../components/DocDiagram.vue";
import RichText from "../../components/RichText.vue";
import type { DiagramSpec } from "../../utils/diagram";
import { JLPT_RANGE } from "~~/shared/jlpt";
import { DATA_SOURCES, SOURCES } from "~~/shared/sources";

const provenance = [
  {
    field: "kana, meaning, level",
    source:
      "The pool (`data/reference/n*-reference.json`), after the `shared/meanings.ts` corrections.",
  },
  {
    field: "pos",
    source: "JMdict's tags for the sense matching the pool meaning, verbatim.",
  },
  {
    field: "priority",
    source:
      "JMdict's `ke_pri` and `re_pri` codes for the spelling and reading, verbatim.",
  },
  {
    field: "register, field, dialect",
    source:
      "JMdict's `misc` tags that name a register (colloquial, polite, slang…, the list is `REGISTER_TAGS`), and its `field` and `dial` tags, verbatim, for the sense(s) matching the pool meaning; a tag is kept only if every matched sense carries it.",
  },
  {
    field: "pitch",
    source:
      "The Kanjium accent list: the mora after which the pitch falls (0: it does not), for the exact spelling and reading; the accents UniDic gives for that spelling and reading too, in Kanjium's order.",
  },
  {
    field: "stratum",
    source:
      "A katakana spelling (hybrid when mixed with kanji), a loan source named by the text or by JMdict, KANJIDIC2's on/kun analysis of the spelling, or else the text's “Middle Chinese” or “Old Japanese”. Omitted when none settles it (irregular spellings).",
  },
  {
    field: "sources[]",
    source:
      "The lines of Wiktionary's Etymology section for this reading, verbatim.",
  },
  {
    field: "morphemes[]",
    source:
      "Parsed from those lines, or a literal gloss plus KANJIDIC2 readings, or per-kanji KANJIDIC2 data; only if the parts spell the word and join to its reading.",
  },
  {
    field: "processes",
    source:
      "Keyword tags found in the quoted text (`rendaku`, `clipping`, `ateji`…), plus `wasei`, `ateji` and `borrowing` where JMdict records them for the matched sense (a note on a spelling or reading counts only for a word written with kanji).",
  },
  {
    field: "examples[]",
    source:
      "Tatoeba sentences the pinned export indexes under the word, as picked by `scripts/lib/example-sentences.mjs`: with a translation, short, the word's own form in the text. Quoted unchanged. `furigana` is Tatoeba's own transcription of the sentence, kept by `scripts/lib/furigana.mjs` only where each kanji's reading is one KANJIDIC2 (or JMdict, for the whole word) gives it and a contributor wrote it, or kuromoji or Tatoeba's index agrees. Where the older checks (the index, JMdict) disagree with a contributor, the contributor's reading is used; where they disagree with Tatoeba's software, theirs is.",
  },
  { field: "wiktionaryDump", source: "The snapshot's `dump` date." },
  { field: "headline", source: "Hand-written (`data/word-plan/`)." },
];

const build: Required<Pick<DiagramSpec, "nodes" | "edges">> = {
  nodes: [
    {
      id: "wl",
      label: "Word lists",
      sub: "pinned commits",
      col: 0,
      row: 0,
      kind: "actor",
    },
    {
      id: "jam",
      label: "JMdict, KANJIDIC2",
      sub: "checksum-verified",
      col: 0,
      row: 1,
      kind: "actor",
    },
    {
      id: "wik",
      label: "Wiktionary dump",
      sub: "Etymology sections",
      col: 0,
      row: 2.2,
      kind: "actor",
    },
    {
      id: "refb",
      label: "data:reference",
      sub: "+ meanings.ts fixes",
      col: 1,
      row: 0.5,
    },
    {
      id: "etyb",
      label: "data:etymology",
      sub: "from a pinned dump",
      col: 1,
      row: 2.2,
    },
    {
      id: "ref",
      label: "Reference snapshots",
      sub: "data/reference/",
      col: 2,
      row: 0.5,
      kind: "store",
    },
    {
      id: "plan",
      label: "Headlines",
      sub: "data/word-plan/",
      col: 2,
      row: 1.35,
      kind: "actor",
    },
    {
      id: "ety",
      label: "Etymology pins",
      sub: "data/reference/etymology/",
      col: 2,
      row: 2.2,
      kind: "store",
      w: 176,
    },
    {
      id: "gen",
      label: "data:words",
      sub: "fetches nothing",
      col: 3,
      row: 1.35,
      kind: "check",
    },
    {
      id: "words",
      label: "Entries",
      sub: "data/words/*.json",
      col: 3,
      row: 2.7,
      kind: "store",
    },
  ],
  edges: [
    { from: "wl", to: "refb", out: "r", into: "l" },
    { from: "jam", to: "refb", out: "r", into: "l" },
    { from: "wik", to: "etyb" },
    { from: "refb", to: "ref" },
    { from: "etyb", to: "ety" },
    { from: "ref", to: "gen", out: "r", into: "l" },
    { from: "plan", to: "gen" },
    { from: "ety", to: "gen", out: "r", into: "l" },
    { from: "gen", to: "words", out: "b", into: "t" },
  ],
};

const checks: Required<Pick<DiagramSpec, "nodes" | "edges">> = {
  nodes: [
    { id: "ref", label: "Reference snapshots", col: 0, row: 0, kind: "store" },
    { id: "ety", label: "Etymology pins", col: 0, row: 1.2, kind: "store" },
    {
      id: "words",
      label: "Entries",
      sub: "data/words/*.json",
      col: 0,
      row: 2.4,
      kind: "store",
    },
    {
      id: "tests",
      label: "test/content",
      sub: "verifies each claim",
      col: 1,
      row: 1.2,
      kind: "check",
    },
    {
      id: "ci",
      label: "pnpm test",
      sub: "CI",
      col: 2,
      row: 1.2,
      kind: "check",
    },
    {
      id: "pass",
      label: "Passes",
      sub: "every entry checks out",
      col: 3,
      row: 0.4,
      kind: "actor",
    },
    {
      id: "fail",
      label: "Fails",
      sub: "a wrong claim found",
      col: 3,
      row: 2,
      kind: "ghost",
    },
  ],
  edges: [
    { from: "ref", to: "tests", out: "r", into: "l" },
    { from: "ety", to: "tests" },
    { from: "words", to: "tests", out: "r", into: "l" },
    { from: "tests", to: "ci" },
    { from: "ci", to: "pass", out: "r", into: "l" },
    { from: "ci", to: "fail", out: "r", into: "l" },
  ],
};
</script>
