<template>
  <div
    class="min-h-screen bg-[#FDFBF7] dark:bg-[#0B0E14] text-stone-900 dark:text-stone-100 selection:bg-primary-500/20 flex flex-col"
  >
    <!-- Season-patterned backdrop (shoji grid / ripples / hishi lattice / snow) -->
    <div class="season-backdrop" />

    <AppHeader />

    <main
      class="relative z-10 container mx-auto px-4 max-w-4xl py-12 flex-1 prose dark:prose-invert"
    >
      <NuxtLink
        to="/#docs"
        class="kicker text-stone-400 dark:text-stone-500 no-underline hover:text-primary-500 transition-colors"
      >
        &larr; Documentation
      </NuxtLink>
      <h1
        class="text-3xl sm:text-4xl font-serif font-bold mb-4 mt-4 text-stone-900 dark:text-white"
      >
        Data Integrity & Attribution
      </h1>

      <p class="mb-8 text-gray-700 dark:text-gray-300 text-lg">
        NipponDaily teaches Japanese, so a wrong reading, meaning or origin is a
        bug. Every word's reading, level and meaning traces to a licensed
        dictionary, every origin claim to a quoted line of a pinned Wiktionary
        revision, and the tests check both against committed evidence.
      </p>

      <h2
        id="data-attribution"
        class="text-3xl font-serif font-bold mt-12 mb-6 text-primary-500 border-b border-gray-200 dark:border-gray-800 pb-2"
      >
        1. Data & Sources
      </h2>

      <div class="overflow-x-auto mb-6">
        <table class="min-w-full border-collapse text-sm">
          <thead>
            <tr class="border-b border-gray-300 dark:border-gray-700">
              <th class="py-2 px-2 text-left font-bold">Data</th>
              <th class="py-2 px-2 text-left font-bold">Source</th>
              <th class="py-2 px-2 text-left font-bold">Lives in</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-200 dark:divide-gray-800">
            <tr>
              <td class="py-2 px-2 align-top">JLPT vocabulary (N5–N2)</td>
              <td class="py-2 px-2">
                <a
                  href="https://github.com/elzup/jlpt-word-list"
                  target="_blank"
                  rel="noopener"
                  >elzup/jlpt-word-list</a
                >
                (one CSV per level), cross-referenced against JMdict and
                KANJIDIC2 from a checksum-verified
                <code>jamdict-data</code> release
              </td>
              <td class="py-2 px-2 font-mono text-xs align-top">
                data/reference/n{5,4,3,2}-reference.json
              </td>
            </tr>
            <tr>
              <td class="py-2 px-2 align-top">Daily words</td>
              <td class="py-2 px-2">
                Generated by <code>pnpm data:words</code> from the word lists,
                JMdict/KANJIDIC2 and
                <a
                  href="https://en.wiktionary.org"
                  target="_blank"
                  rel="noopener"
                  >English Wiktionary</a
                >
                quoted through a snapshot pinned per revision id. Only the
                headline is hand-written
              </td>
              <td class="py-2 px-2 font-mono text-xs align-top">
                data/words/YYYY-MM.json
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <div class="my-10 bg-stone-50 dark:bg-stone-900/50 p-4 season-box">
        <h3
          class="text-center mb-6 text-xl font-semibold text-gray-800 dark:text-gray-200"
        >
          The Data Pipeline, End to End (Zoomable)
        </h3>
        <MermaidDiagram id="data-pipeline-diag" :code="dataPipelineDiagram" />
        <p class="text-center text-xs text-gray-500 mt-4 italic">
          Top: what the site serves. Bottom: an independent offline snapshot the
          top is checked against in CI.
        </p>
      </div>

      <ol
        class="list-decimal pl-6 space-y-3 mb-8 text-gray-700 dark:text-gray-300"
      >
        <li>
          <strong>Correct the word list.</strong>
          <code>shared/meanings.ts</code> holds form corrections for words the
          source list gets wrong and fuller meanings (早い as “early; quick,
          soon”), applied with <code>servedVocab()</code> whenever a snapshot is
          built.
        </li>
        <li>
          <strong>Snapshot the evidence.</strong>
          <code>pnpm data:reference</code> (N5) and
          <code>pnpm data:reference:jlpt</code> (N4–N2) rebuild committed
          JMdict/KANJIDIC2 snapshots
          (<code>data/reference/n5-reference.json</code>, with
          <code>n4</code>–<code>n2</code> alongside) from the same word-list
          commits and a checksum-verified <code>jamdict-data</code> release. The
          two builds are independent, so a mistake in one can't hide in the
          other.
        </li>
        <li>
          <strong>Pin the origins.</strong>
          <code>pnpm data:etymology</code> commits the plain text of each daily
          word's Wiktionary <em>Etymology</em> section to
          <code>data/reference/etymology/</code>, each page pinned to a revision
          id.
        </li>
        <li>
          <strong>Generate the entries.</strong>
          <code>pnpm data:words</code> builds each day's entry from
          <code>data/word-plan/</code> (date, word, headline) and those
          committed snapshots. It fetches nothing.
        </li>
      </ol>

      <div
        class="p-4 season-box bg-stone-50 dark:bg-stone-900 border border-stone-200 dark:border-stone-800 text-sm"
      >
        <p class="font-semibold mb-2">Attribution</p>
        <p class="mb-2">
          JMdict and KANJIDIC2 are property of the
          <a href="https://www.edrdg.org/" target="_blank" rel="noopener"
            >Electronic Dictionary Research and Development Group</a
          >, used under CC BY-SA 4.0 via the
          <a
            href="https://pypi.org/project/jamdict-data/"
            target="_blank"
            rel="noopener"
            >jamdict-data</a
          >
          release.
        </p>
        <p class="mb-2">
          Etymology text is quoted from
          <a href="https://en.wiktionary.org" target="_blank" rel="noopener"
            >English Wiktionary</a
          >
          under
          <a
            href="https://creativecommons.org/licenses/by-sa/4.0/"
            target="_blank"
            rel="noopener"
            >CC BY-SA 4.0</a
          >. Each entry links the exact revision it quotes and quotes it
          verbatim; the one-line headline is NipponDaily's own.
        </p>
        <p class="m-0">
          The word lists come from the community list originally compiled at
          tanos.co.uk, via elzup/jlpt-word-list (MIT licence). Kana conversion
          in the checks uses
          <a
            href="https://github.com/WaniKani/WanaKana"
            target="_blank"
            rel="noopener"
            >wanakana</a
          >
          (MIT licence).
        </p>
      </div>

      <h2
        class="text-3xl font-serif font-bold mt-16 mb-6 text-primary-500 border-b border-gray-200 dark:border-gray-800 pb-2"
      >
        2. Content-Accuracy CI Checks
      </h2>

      <p class="mb-6">
        Dictionary data isn't in the repo's tests, and etymology isn't in a
        dictionary at all. So the evidence is committed to the repo and the
        content tests (<code>test/content/</code>, their own Vitest project, run
        by <code>pnpm test</code> in CI) check every fact against it. Daily-word
        entries go further: only the one-line headline is hand-written.
        Everything else is <strong>generated from these sources</strong> by
        <code>pnpm data:words</code>, so no sentence about a word's origin is
        ever written by a person or a model.
      </p>

      <ul class="list-disc pl-6 mb-6 space-y-3">
        <li>
          <strong>Every served word, at every level</strong>
          (<code>vocabulary.test.ts</code>, mirrored for N4/N3/N2):
          <ul class="list-disc pl-6 mt-2 space-y-1">
            <li>
              is in JMdict <em>with that reading</em> (single-kanji affixes like
              ～月 may use a KANJIDIC2 reading instead);
            </li>
            <li>has no meaning that reverses JMdict's (this ↔ that…);</li>
            <li>
              has its reading attested by JMdict
              (<code>reading-attested.test.ts</code>);
            </li>
            <li>
              has every enrichment in <code>shared/meanings.ts</code> backed by
              JMdict (each <code>;</code>-separated sense shares a content word
              with a JMdict gloss), and a reference snapshot that is not stale.
            </li>
          </ul>
        </li>
        <li>
          <strong>Every daily-word entry</strong>
          (<code>words.test.ts</code>):
          <ul class="list-disc pl-6 mt-2 space-y-1">
            <li>
              is a real word from the JLPT lists whose reading, level and
              meaning equal the word list's (after
              <code>shared/meanings.ts</code>);
            </li>
            <li>
              carries JMdict's own part-of-speech tags for that word, verbatim
              (no tag JMdict doesn't give for it);
            </li>
            <li>
              quotes only lines of Wiktionary's Etymology section for the word's
              <strong>own reading</strong> (a page with several readings has one
              section each), every line <strong>verbatim</strong> at the
              revision the entry names;
            </li>
            <li>
              shows morphemes only when the parts literally spell the word and
              their readings join to its reading; a single-kanji part needs a
              reading KANJIDIC2 lists (else it is marked
              <code>irregular</code>) and a gloss that KANJIDIC2 or the cited
              text backs. When the text gives no split of an all-kanji word,
              each part is one of its kanji with KANJIDIC2's reading and one of
              its own meanings, and the page says so;
            </li>
            <li>
              has a headline that mentions only Japanese its evidence or the
              pool contains;
            </li>
            <li>
              quotes a hedged line whenever it is tagged <code>unclear</code>,
              and no snapshot pin outlives its entry;
            </li>
            <li>
              equals, field for field, what the generator derives from the plan
              and the sources (<code>word-generation.test.ts</code>), so a
              derived field can't be edited by hand or left behind when a source
              changes.
            </li>
          </ul>
        </li>
      </ul>

      <div
        class="my-8 p-4 season-box border border-amber-200 dark:border-amber-800 bg-amber-50 dark:bg-amber-900/20 text-sm"
      >
        <strong>What these checks cannot prove:</strong> that a quote is
        <em>true</em> (only that Wiktionary says it, at that revision), or that
        a headline is a fair hook. The headline is the one hand-written line and
        makes no claim the page relies on. Where Wiktionary hedges, the entry
        quotes the hedge and flags it instead of choosing.
      </div>

      <h3
        class="text-xl font-semibold mt-8 mb-4 text-stone-800 dark:text-stone-200"
      >
        When a check fails
      </h3>

      <ul class="list-disc pl-6 mb-6 space-y-3">
        <li>
          <strong>A word isn't in JMdict</strong> → add an entry to
          <code>VOCAB_FORM_CORRECTIONS</code> in
          <code>shared/meanings.ts</code>, then run
          <code>pnpm data:reference</code> (or
          <code>pnpm data:reference:jlpt</code> for N4–N2).
        </li>
        <li>
          <strong>A meaning isn't backed</strong> → reword it to match JMdict or
          drop the sense; don't widen the checker.
        </li>
        <li>
          <strong>A quote isn't found</strong> → copy it again from the
          snapshot, or run
          <code>pnpm data:etymology --refresh &lt;term&gt;</code> if the page
          was edited and you mean to re-pin it. Never loosen a quote.
        </li>
        <li>
          <strong>A morpheme, tag or quote is wrong</strong> → entries are
          derived, so don't edit them: fix the source (a correction in
          <code>shared/meanings.ts</code>, a re-pinned page) or the parsing in
          <code>scripts/lib/word-entry.mjs</code>, then run
          <code>pnpm data:words</code>.
        </li>
        <li>
          <strong>The headline mentions Japanese no evidence contains</strong> →
          reword it in <code>data/word-plan/</code>.
        </li>
      </ul>

      <h3
        class="text-xl font-semibold mt-8 mb-4 text-stone-800 dark:text-stone-200"
      >
        Updating the evidence
      </h3>

      <p class="mb-6">
        The sources are pinned in two places:
        <code>WORD_LIST_SOURCES</code> in
        <code>scripts/word-list-source.mjs</code> (shared by both reference
        builders, so they always read the same word lists) and
        <code>JAMDICT_SOURCE</code> in <code>scripts/lib/jamdict.mjs</code>.
        After moving a pin, run <code>pnpm data:reference</code> and
        <code>pnpm data:reference:jlpt</code> together and review the diffs. The
        reference builders need Node 22.13 or newer (<code>node:sqlite</code>)
        plus <code>tar</code> and <code>xz</code>.
      </p>

      <p class="mb-6">
        Wiktionary pins are each term's <code>revid</code> in the snapshot. To
        add a month, write <code>data/word-plan/YYYY-MM.json</code> (date, word
        and headline per day), run <code>pnpm data:etymology --terms …</code> to
        pin the pages (new terms are fetched at their current revision, existing
        ones keep their pin), run <code>pnpm data:words</code>, then register
        the generated <code>data/words/YYYY-MM.json</code> in
        <code>shared/words.ts</code>. Re-pin one term deliberately with
        <code>pnpm data:etymology --refresh &lt;term&gt;</code> and review the
        diff.
      </p>

      <p class="mb-6">
        Two Markdown files in the repo's <code>docs/</code> folder cover the
        same ground for people working on the data:
        <code>docs/content-accuracy.md</code> is the short version of this page,
        and <code>docs/authoring-checklist.md</code> walks through adding a
        month, writing an entry, correcting a word and refreshing the sources.
        They are not served by the site.
      </p>
    </main>

    <AppFooter />
  </div>
</template>

<script setup lang="ts">
import { usePageSeo } from "../../composables/usePageSeo";
import AppHeader from "../../components/AppHeader.vue";
import AppFooter from "../../components/AppFooter.vue";

const dataPipelineDiagram = `
flowchart TD
    subgraph LIVE["What the site serves"]
        direction TB
        Plan["data/word-plan/*.json
(hand-written headlines)"]
        Gen["pnpm data:words"]
        Words["data/words/*.json
daily-word entries (generated)"]
        WordAPI["GET /api/daily-word
GET /api/word-calendar"]

        Plan --> Gen
        Gen --> Words
        Words --> WordAPI
    end

    subgraph TRUTH["Ground truth — checked independently in CI"]
        direction TB
        SamePin["scripts/word-list-source.mjs
(pinned commits of the word lists)"]
        Jamdict["jamdict-data
checksum-verified JMdict/KANJIDIC2"]
        RefBuild["pnpm data:reference
pnpm data:reference:jlpt"]
        RefJSON["data/reference/n{5,4,3,2}-reference.json
(committed snapshots)"]
        Wikt["English Wiktionary
Japanese Etymology sections"]
        EtyBuild["pnpm data:etymology
pinned per revision id"]
        EtyJSON["data/reference/etymology/
(committed snapshot)"]
        ContentTests["test/content/*
vocabulary · words"]

        SamePin --> RefBuild
        Jamdict --> RefBuild
        RefBuild --> RefJSON
        Wikt --> EtyBuild
        EtyBuild --> EtyJSON
        RefJSON --> ContentTests
        EtyJSON --> ContentTests
    end

    Meanings["shared/meanings.ts
corrections + enrichments"] -.-> RefBuild
    RefJSON --> Gen
    EtyJSON --> Gen
    Words -. "readings, meanings, tags,
morphemes, quotes, headline" .-> ContentTests
    ContentTests --> CI{"pnpm test (CI)"}
    CI -- "wrong reading, meaning,
quote or invented word found" --> Fail(["❌ CI fails"])
    CI -- "every entry checks out" --> Pass(["✅ CI passes"])

    WordAPI --> Pages["/ · /words · /words/[date]"]
`;

usePageSeo({
  title: "Data integrity & attribution",
  description:
    "How every reading, meaning and origin is checked against pinned sources, and the licences behind them.",
  path: "/docs/data-integrity",
});
</script>

<style scoped>
@reference "../../assets/css/tailwind.css";

h1 {
  @apply text-3xl font-serif font-bold mb-6 text-stone-900 dark:text-white;
}
h2 {
  @apply text-2xl font-serif font-bold mt-12 mb-4 text-primary-500;
}
p {
  @apply mb-4 text-gray-700 dark:text-gray-300;
}
</style>
